name: museum_app
description: A modern museum application

# Version format is major.minor.patch+build_number
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  provider: ^6.1.1
  get_it: ^7.6.7
  dio: ^5.4.0
  flutter_barcode_scanner: ^2.0.0
  cached_network_image: ^3.3.1
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  sqflite: ^2.3.0
  path: ^1.8.3
  audioplayers: ^5.2.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8

# Flutter specific configurations can be added here
flutter:
  uses-material-design: true

  # Add assets configuration
  assets:
    - assets/
    - assets/audio/
  fonts:
    - family: Playfair
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
          weight: 700
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Thin.ttf
          weight: 100
        - asset: assets/fonts/Urbanist-Light.ttf
          weight: 300
        - asset: assets/fonts/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Urbanist-Bold.ttf
          weight: 700

  generate: true
