name: museum_app
description: Culture Connect - Your intelligent museum guide with AI-powered art exploration

# Version format is major.minor.patch+build_number
# version: MAJOR.MINOR.PATCH+BUILD_NUMBER
# - Increment MAJOR for breaking changes
# - Increment MINOR for new features
# - Increment PATCH for bug fixes
# - Increment BUILD_NUMBER for each release
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  provider: ^6.1.1
  get_it: ^7.6.7
  dio: ^5.4.0
  mobile_scanner: ^5.0.0
  cached_network_image: ^3.3.1
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  sqflite: ^2.3.0
  path: ^1.8.3
  audioplayers: ^5.2.1
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  supabase_flutter: ^2.10.1
  google_generative_ai: ^0.4.0
  image_picker: ^1.1.2
  share_plus: ^10.1.2
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8

# Flutter specific configurations can be added here
flutter:
  uses-material-design: true

  # Add assets configuration
  assets:
    - assets/
    - assets/audio/
    - assets/data/
    - .env
  fonts:
    - family: Playfair
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
          weight: 700
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Thin.ttf
          weight: 100
        - asset: assets/fonts/Urbanist-Light.ttf
          weight: 300
        - asset: assets/fonts/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Urbanist-Bold.ttf
          weight: 700

  generate: true
